### ISSUE TITLE
Ajuster les seuils d'envoi des newsletter indicateurs

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#100]
Voici les seuils à respecter pour l'envoi des indicateurs
<img width="1346" alt="Capture d’écran 2022-03-24 à 10 49 20" src="https://user-images.githubusercontent.com/63290799/160373702-755fd58f-f17f-4d7d-ace1-a40e2dbe2672.png">

Attention : le schéma est faux pour l'indice UV en cas de vigilance => voir commentaire plus bas

**Comment by annepoirot** [comment]
@l-vincent-l :
- Vérifier que l'envoi est comme sur le schéma pour la fréquence quotidienne ET en cas de vigilance
- Vérifier que l'envoi des recommandations n'est pas conditionnés par l'envoi des indicateurs comme du temps ou on avait qu'une recommandation (notamment RAEP et épisode de pollution en quotidien)
- Pour l'indice UV en cas de vigilance => on ne prend pas en compte le filtre enfant pour le moment. Du coup on envoie en cas de vigilance à partir de l'indice UV 6.

**Comment by fcoufour** [comment]
PR correspondante ici : https://github.com/betagouv/recosante-api/pull/376

**Comment by annepoirot** [comment]
Dernier point à vérifier : l'envoi des recommandations n'est pas conditionnés par l'envoi des indicateurs comme du temps ou on avait qu'une recommandation (notamment RAEP et épisode de pollution en quotidien)

**Comment by fcoufour** [comment]
J'ai mis des remarques lors de la review du code. A voir ensemble.
J'ai pas trouvé dans le code le dernier point sur l'envoi des recommandations
