### ISSUE TITLE
Ajouter une mention sur les données personnelles dans le template d'envoi d'indicateurs et de NL hebdo

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#106]
"En savoir plus sur la gestion de vos données personnelles"

et renvoie vers la page https://recosante.beta.gouv.fr/politiquedeconfidentialite

ET modifier le nom de la page "politique de confidentialite" vers "donneespersonnelles"

**Comment by fcoufour** [comment]
PR front-end : https://github.com/betagouv/recosante/pull/212
Email TODO
