### ISSUE TITLE
Ajouter une mention pour valoriser le changement de ville

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#108]
On teste un encart provisoire pour tester l'intérêt en haut du mail type : 

"Vous partez en vacances ? Vous pouvez à tout moment consulter les indicateurs d'une autre ville directement sur le tableau de bord Recosanté, ou bien modifier la ville pour laquelle vous recevez les e-mails Recosanté sur votre compte"
@MarinePurson tu as peut-etre une meilleure tournure ? 

On aimerait aussi voir pour mettre plus en avant le fait de modifier ses préférences => pas assez visible actuellement, pourrait être un bouton plus visible avant ou après les boutons partager. Et aussi la formulation n'est pas idéale (peut-être mettre "modifier mes préférence d'envoi").

**Comment by MarinePurson** [comment]
Proposition : 
"**Vous partez en vacances ? Consultez à tout moment les indicateurs de la commune directement sur le tableau de bord Recosanté !** 
Pour recevoir directement les informations pour votre lieu de vacances, modifiez la commune sur votre compte [lien vers le compte]."

**Comment by fcoufour** [comment]
J'ai mis ceci en header pour tous.
<img width="539" alt="header-vacances" src="https://user-images.githubusercontent.com/23194091/174568193-0a676825-bc07-431f-aade-702ae7976bec.png">

Et j'ai également mis ceci en footer pour ceux qui n'avait pas l'incentive "Vigilance météo et Indice UV".
<img width="586" alt="footer-modifier" src="https://user-images.githubusercontent.com/23194091/174568344-e23b9236-455e-4668-b56a-11a91156de15.png">

Est-ce que ça vous convient ? @annepoirot @MarinePurson
