### ISSUE TITLE
L'échelle de couleur pour l'indice QA et le RAEP manque de qualificatif 

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#11]
Est-ce qu'on ne pourrait pas indiquer au minimum le premier et le dernier qualificatif ? 

Dans la maquette initialement, il y avait une proposition avec une flèche, c'était plus difficile à mettre en place ?

**Comment by florianpanchout** [comment]
Le texte n'est pas lisible sur mobile lorsqu'on l'intègre à l'échelle. J'ai ajouté une flèche. Ça te va ?

**Comment by annepoirot** [comment]
Je préfère sans la flèche je pense. En fait le soucis, même avec la flèche, c'est que l'échelle n'a pas de signification comme elle est là, d'où la proposition de mettre au moins le qualificatif de début et de fin. Mais effectivement c'est pas top si pas lisible sur mobile..

**Comment by florianpanchout** [comment]
Je ne suis pas sur que mettre une légende aide à la compréhension. Ce qui est interessant c'est de savoir ou l'on se situe sur l'échelle, pas le nom des paliers non ?
