### ISSUE TITLE
Intégrer un encart sur les eaux de baignade dans le mail indicateurs

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#112]
Pour les encadrés du mail quotidien, je mettrais : 

en haut :
Cet été, vous souhaitez vous baigner en sécurité ?
Consultez la qualité de l'eau sur votre lieu de baignade sur le tableau de bord Recosanté ! 
& Bouton "Consulter la qualité de l'eau de baignade"

en bas :
Vous déménagez ou vous partez en vacances ?
Vous pouvez modifier  à tout moment votre commune directement sur votre compte, ainsi que vos préférences d’envoi (choix des indicateurs environnementaux, fréquence, etc.).  Vous pouvez aussi consulter les indicateurs de votre nouvelle commune sur le tableau de bord Recosanté.
& Bouton "Modifier ma commune" ou "Modifier mes préférences"

**Comment by l-vincent-l** [comment]
Un brouillon est disponible ici https://my.sendinblue.com/camp/template/3561/message-setup

**Comment by l-vincent-l** [comment]
C’est fait

**Comment by annepoirot** [comment]
Modifier le lien dans le premier encart pour renvoyer vers la home en faisant un lien tracké

**Comment by annepoirot** [comment]
@l-vincent-l on peut supprimer cette partie : 
<img width="497" alt="Capture d’écran 2022-07-25 à 10 56 22" src="https://user-images.githubusercontent.com/63290799/180738607-6fff2147-d54a-4353-a0b1-99c271aa73b7.png">

**Comment by annepoirot** [comment]
Et cette partie ne doit pas être conditionnelle, elle doit toujours s'afficher 
<img width="499" alt="Capture d’écran 2022-07-25 à 10 56 58" src="https://user-images.githubusercontent.com/63290799/180738741-d78c14ae-6985-4b01-9be9-9b5dd640ce75.png">

**Comment by annepoirot** [comment]
To do : 
- vérifier les conditions car parfois je reçois certains encart du bas et parfois non. 
- Modifier le code sur le repo github

**Comment by fcoufour** [comment]
A date, voici ce qu'il y a dans les templates :

- en header :
<img width="665" alt="email-header" src="https://user-images.githubusercontent.com/23194091/188385524-b453d2fb-7cca-4155-9d98-dae3e359f4c8.png">

- en footer :
<img width="677" alt="email-footer" src="https://user-images.githubusercontent.com/23194091/188385554-9a73cb53-c3a9-4031-9741-fab754c44434.png">

**Comment by fcoufour** [comment]
70% de l'audience a eu comme footer "Deux nouveaux indicateurs sont disponibles !".
30% a eu "Vous déménagez ou vous partez en vacances ?"

**Comment by fcoufour** [comment]
J'ai fait les stats à la mano ici sur 8 jours concernant les liens des header et footer : https://docs.google.com/spreadsheets/d/1kr157eBnDc-XOweZgnEN8CW4PLlLbNT21OBQOV64wr8

- Autant de clics en footer pour "Deux nouveaux indicateurs sont disponibles !" et "Vous déménagez ou vous partez en vacances ?" (après redressement sur le volume)
- 1,75 fois plus de clics sur le header "Cet été, vous souhaitez vous baigner en sécurité ?"
- De l'ordre de 30 clics tous les jours
