### ISSUE TITLE
Le RAEP ne s'affiche pas dans le nouveau template

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#12]
L'attribut contact.RISQUE_POLLENS n'existe pas dans sendinblue, on a show.raep et raep 

L'affichage du RAEP est conditionné par : 
- si la personne est allergique, elle reçoit le RAEP quand RAEP supérieur ou égal à 1 
- si la personne n'est pas allergique, elle reçoit le RAEP quand RAEP supérieur ou égal à 4

**Comment by florianpanchout** [comment]
Je ne peux pas afficher "nul", "très faible", etc... avec juste 0, 1, 2, 3 4.

Pareil pour la couleur qui est tout le temps à #fff

Voir : https://github.com/betagouv/recosante-mail/issues/8

**Comment by annepoirot** [comment]
Yes @l-vincent-l va regarder cet aprem. Merci !

**Comment by l-vincent-l** [comment]
Ce problème a été résolu dans le projet ecosanté
