### ISSUE TITLE
L'email de confirmation est différent du nouveau template

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#13]
Il s'agirait de reprendre le template du mail quotidien en ajoutant un encadré au début disant 👍 

Merci pour votre inscription à Recosanté !
Voici les informations du jour sur la qualité de l'air autour de chez vous.

Similaire au précédent mail de confirmation : https://my.sendinblue.com/camp/template/108/message-setup

**Comment by florianpanchout** [comment]
Fait

**Comment by l-vincent-l** [comment]
On peut voir dans les logs des emails transactionnels de SendinBlue que le bon template est envoyé.
