### ISSUE TITLE
Modifier les couleurs de l'échelle du RAEP

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#14]
La couleur du qualificatif de l'indice pollen ne correspond pas aux couleurs de l'échelle. (#fffd54 au lieu de #FDD504 pour moyen)

**Comment by annepoirot** [comment]
@l-vincent-l

**Comment by l-vincent-l** [comment]
Tu prends quelle échelle ? Je pense que si le moyen est faux, le reste doit l’être aussi.
Je me suis basé sur ce qu’il y a en bas ici https://pollens.fr/

**Comment by annepoirot** [comment]
Ah oui effectivement l'échelle actuelle du template n'est pas celle du site pollen. Ca ne résout pas notre problème de visibilité du jaune haha

**Comment by l-vincent-l** [comment]
Ah ok, on parle de cette échelle, je vais faire ça alors !

**Comment by l-vincent-l** [comment]
Corrigé ici https://github.com/betagouv/ecosante/commit/9612743b44dae989e133e5f66b159de318a8228b

**Comment by florianpanchout** [comment]
J'ai pris cette page comme référence pour le visuel : https://www.atmo-hdf.fr/acceder-aux-donnees/le-risque-d-allergie-aux-pollens.html

Ce n'est pas la bonne ?

**Comment by annepoirot** [comment]
Je crois qu'ils sont pas vraiment fixé sur leur échelle haha... Gardons ça pour le moment :)

**Comment by annepoirot** [comment]
On a eu un retour du RNSA et ils souhaiteraient qu'on utilise les couleurs qui sont ici : https://www.atmo-hdf.fr/acceder-aux-donnees/le-risque-d-allergie-aux-pollens.html

**Comment by annepoirot** [comment]
Il faudrait re modifier comme avant dans recosante-api et mettre dans l'échelle du mail 
            0: "#fff",
            1: "#75f94c",
            2: "#377d22",
            3: "#fffd54",
            4: "#ef8641",
            5: "#ea3522"

**Comment by florianpanchout** [comment]
Pas sur de comprendre ton retour. On utilise déjà les couleurs de cette page (https://www.atmo-hdf.fr/acceder-aux-donnees/le-risque-d-allergie-aux-pollens.html)

Les couleurs que tu cites après sont celles de https://pollens.fr/.

Si on utilise celles ci, il faudra changer la mise en page du mail

**Comment by annepoirot** [comment]
Oui voila, en fait les couleurs de https://www.atmo-hdf.fr/acceder-aux-donnees/le-risque-d-allergie-aux-pollens.html ne sont pas correctes et ne proviennent pas du RNSA. Il faut effectivement mettre les couleurs du site du RNSA https://pollens.fr/

**Comment by florianpanchout** [comment]
Du coup il faut soit changer la mise en page, soit ne pas afficher la couleur du tout

**Comment by annepoirot** [comment]
A cause du blanc ? Le RAEP n'est jamais envoyé lorsqu'il est nul

**Comment by florianpanchout** [comment]
On reviens au problème initial : Les couleurs pour les niveaux 1 et 3 ne sont pas lisibles (et aucune n'est accessible)

**Comment by l-vincent-l** [comment]
J’ai ajouté dans send_in_blue un paramètre par allergène.
Chaque paramètre est nommé `ALLERGENE_{NOM_ALLERGENE}` (avec `NOM_ALLERGENE` en majuscule)
La liste des allergènes est la suivante :
 * cypres
 * noisetier
 * aulne
 * peuplier
 * saule
 * frene
 * charme
 * bouleau
 * platane
 * chene
 * olivier
 * tilleul
 * chataignier
 * rumex
 * graminees
 * plantain
 * urticacees
 * armoises
 * ambroisies

J’aurai voulu faire plus propre avec un dictionnaire mais send in blue ne me le permet pas.

**Comment by florianpanchout** [comment]
Aha je me demandais comment tu allais faire
