### ISSUE TITLE
Le lien vers "modifier son profil" ne fonctionne pas 

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#16]
Retour d'un utilisateur sur ce lien : https://recosante.beta.gouv.fr/profil/?user=VfUXIrlZ

**Comment by florianpanchout** [comment]
L'api me renvoie "ménage" au lieu de "menage". 

J'ai fait en sorte que le front ne plante plus lorsqu'il reçoit une valeur qui n'existe pas, donc son profil s'affiche maintenant correctement mais sans la valeur menage sélectionnée.

@l-vincent-l Ce serait bien de verifier comment cette valeur est arrivée la
