### ISSUE TITLE
Les départements n'ont pas toujours les bonnes préposition

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#17]

**Comment by florianpanchout** [comment]
@l-vincent-l Dans l'idéal il me faudrait une variable contenant la préposition en fonction du département

**Comment by annepoirot** [comment]
J'ai l'impression qu'il n'y a pas de façon facile de l'obtenir à par de produire la base... d'autres idées moins manuelles ? Si non, je m'en occuperai !

**Comment by annepoirot** [comment]
Ci-joint les départements et leurs préposition 
[Département français_MP.xlsx](https://github.com/betagouv/recosante-mail/files/6244725/Departement.francais_MP.xlsx)
