### ISSUE TITLE
Afficher la liste des principaux allergènes

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante-mail#26]
Liée à cette [issue](https://github.com/betagouv/recosante-api/issues/201)
Les allergènes sont dans la colonne ALLERGENES de sendinblue

**Comment by annepoirot** [comment]
Finalement on souhaite ajouter l'ensemble des pollens pour chaque région @l-vincent-l 

Ils s'afficheront sous forme de jauge comme dans la maquette ci-dessous.
![Template NL mai 2021](https://user-images.githubusercontent.com/63290799/116865617-40199180-ac0a-11eb-9d17-4e0066b30329.jpg)

**Comment by florianpanchout** [comment]
C'est fait
