### ISSUE TITLE
Infos manquantes

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#27]
Il me manque les infos suivantes dans le nouveau template de mail (https://my.sendinblue.com/camp/template/526/message-setup) : 

Date de validité des indices : "Prévision pour le 16/04/2021" et "Prévision du 12/04/2021 au 18/04/2021"

Phrase d'intro des recommandations (@annepoirot)

**Comment by annepoirot** [comment]
Pour la phrase d'intro : chaque recommandation est associée à une objectif. Mais du coup je pense qu'il faut encore que @l-vincent-l rajoute un attribut dans sendinblue. Du coup la phrase serait "Aujourd’hui, votre recommandation est un conseil pratique pour [objectif]".

**Comment by annepoirot** [comment]
Pour les dates, du coup la date pour l'indice QA est la date du jour. 

La date pour le RAEP est la semaine.

Pareil je suppose qu'il faut rajouter des attributs ?

**Comment by florianpanchout** [comment]
C'est ajouté au template. 

Il me manque la date de validité de l'indice ATMO (je sais que c'est la date du jour, mais le template ne le sait pas lui). J'ai mis QUALITE_AIR_VALIDITE en nom de variable pour l'instant

**Comment by annepoirot** [comment]
Ok donc on est bon pour l'envoi du nouveau template demain matin @l-vincent-l @florianpanchout  ?

**Comment by annepoirot** [comment]
L'attribut sur la date du jour pour l'indice atmo n'a pas fonctionné @l-vincent-l 
<img width="516" alt="Capture d’écran 2021-05-12 à 10 31 55" src="https://user-images.githubusercontent.com/63290799/117944570-b191c800-b30d-11eb-8bdb-5d005dbc6f9b.png">

**Comment by l-vincent-l** [comment]
Ah oui, j’avais mal compris Florian, je croyais qu’il avait rajouté le paramètre dans send in blue
