### ISSUE TITLE
Modifier les précisions dans la partie sur les indicateurs environnementaux

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#29]
Après discussion avec ATMO, ils souhaiteraient qu'on mette une mention comme quoi l'indice est actualisé dans la journée.

Ainsi je proposais de rajouter "Retrouvez l'indice actualisé ici" avec un lien sur "ici" qui renvoie au site de l'AASQA de l'utilisateur. Et donc d'enlever le "en savoir plus" pour les indice ATMO et RAEP.
<img width="453" alt="Capture d’écran 2021-05-10 à 10 06 13" src="https://user-images.githubusercontent.com/63290799/117627458-7a3de280-b178-11eb-969a-cd56a2159bac.png">

**Comment by l-vincent-l** [comment]
En l’état je trouve ça très étrange comme formulation, j’ai l’impression que ça apporte beaucoup de confusion.

Peut être que quelque chose comme : 
"La prévision peut être mise à jour à 14h, retrouvez-la ici"

Là j’ai l’impression qu’on dit que ce qu’on dit est faux.

**Comment by annepoirot** [comment]
Est-ce qu'on peut mettre la même taille de police pour la phrase sur la mise à jour que la précédente sur les prévision @florianpanchout ?

**Comment by florianpanchout** [comment]
Corrigé
