### ISSUE TITLE
Bug sur la phrase d'introduction

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#30]
<img width="510" alt="Capture d’écran 2021-05-12 à 10 16 01" src="https://user-images.githubusercontent.com/63290799/117942213-1b5ca280-b30b-11eb-9af3-d08782575795.png">

Il faut qu'on rajoute dans le template "Aujourd’hui, votre recommandation est un conseil pratique pour" + [objectif en minuscule]

**Comment by annepoirot** [comment]
Je l'ai rajoutée au template, elle n'y était pas

**Comment by florianpanchout** [comment]
C'est fait

Tu l'avais modifié directement dans Sendinblue ? Je n'ai pas vu de commit.

**Comment by annepoirot** [comment]
Oui j'ai modifié dans sendinblue !
