### ISSUE TITLE
Bug d'affichage dans le mail d'une utilisatrice

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#31]
<img width="777" alt="Capture d’écran 2021-05-12 à 14 53 12" src="https://user-images.githubusercontent.com/63290799/117978325-09422a80-b332-11eb-96c5-6aa1fefea5d5.png">

**Comment by florianpanchout** [comment]
Il s'agit de l'ancien template non ?

**Comment by annepoirot** [comment]
Oui t'as raison, je lui ai écris pour voir si c'est encore le cas. Je te dis si/lorsque j'ai un retour
