### ISSUE TITLE
Modifier la phrase sur la rectification des données

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#32]
Remplacer : Conformément à la réglementation en vigueur, vous disposez d’un droit d’accès, de rectification et de suppression de vos données que vous pouvez exercer par courrier électronique à l'adresse : contact@recosante.beta.gouv.fr

Par : Vous disposez d’un droit d’accès, de rectification et de suppression de vos données que vous pouvez exercer en écrivant à : contact@recosante.beta.gouv.fr

**Comment by florianpanchout** [comment]
Fait
