### ISSUE TITLE
Partie du template illisible en dark mode

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#34]
Retour d'un utilisateur pour les écritures en gris sur fond bleu à cause du dark mode
<img width="526" alt="Capture d’écran 2021-05-13 à 09 55 19" src="https://user-images.githubusercontent.com/63290799/118096285-72c54600-b3d1-11eb-9baf-1232a4b33de7.png">

**Comment by florianpanchout** [comment]
Sur quel client mail ? J'ai modifié le template pour qu'il s'adapte en dark mode

**Comment by annepoirot** [comment]
J'ai demandé à l'utilisateur. Moi c'est sur ma messagerie Mail de mon macbook

**Comment by florianpanchout** [comment]
Tu as encore le problème depuis les modifications ?

**Comment by annepoirot** [comment]
Non c'est bon !
