### ISSUE TITLE
Bug dans l'affichage du mail chez une utilisatrice

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#35]
J'ai reçu ce mail au sujet d'un bug de données QA, mais je vois dans la capture d'écran de la personne qu'il semble avoir un bug d'affichage.
<img width="750" alt="Capture d’écran 2021-05-28 à 15 02 52" src="https://user-images.githubusercontent.com/63290799/119988044-faac7200-bfc5-11eb-89d5-644e7642f702.png">

**Comment by florianpanchout** [comment]
Étrange. Elle utilise quel client mail ? On dirait qu'elle a gardé les anciennes images en cache

**Comment by annepoirot** [comment]
Alors apparemment Marine l'a eu hier aussi et ça n'arrive que sur le qualificatif dégradé. Elle est sur gmail

**Comment by florianpanchout** [comment]
Arf, l'image pour l'indice dégradé n'était pas à jour. C'est corrigé

(Remarque que si personne ne l'a vu, ça voudrait dire que l'on respire tous de l'air moyen depuis quelque jours, ce qui est quand même une bonne nouvelle)

**Comment by annepoirot** [comment]
Haha c'est vrai ! Parfait merci !
