### ISSUE TITLE
Ajouter le lien vers les Pollinarium Sentinelles pour certaines villes

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#36]
En bas à droite de la newsletter, après l'AASQA et le RNSA, on rajoute:

[Pollinariums sentinelles](https://www.alertepollens.org/) 

Seulement pour les villes suivantes :

Abbaretz
Aigrefeuille-sur-Maine
Ancenis-Saint-Géréon
Basse-Goulaine
Blain
Bois-de-Céné
Bouaye
Bouguenais
Bouvron
Brains
Carquefou
Casson
Château-Thébaud
Cheix-en-Retz
Clisson
Corcoué-sur-Logne
Couëron
Couffé
Divatte-sur-Loire
Fay-de-Bretagne
Geneston
Gorges
Grandchamps-des-Fontaines
Haute-Goulaine
Héric
Indre
Joué-sur-Erdre
La Bernardière
La Boissière-du-Doré
La Chapelle-Heulin
La Chapelle-sur-Erdre
La Chevallerais
La Chevrolière
La Grigonnais
La Haie-Fouassière
La Limouzinière
La Marne
La Montagne
La Planche
La Remaudière
Le Bignon
Le Cellier
Le Gâvre
Le Landreau
Le Loroux-Bottereau
Le Pallet
Le Pellerin
Le Temple-de-Bretagne
Les Sorinières
Les Touches
Ligné
Machecoul-Saint-Même
Maisdon-sur-Sèvre
Malville
Mauves-sur-Loire
Mésanger
Monnières
Montbert
Mouzeil
Mouzillon
Nantes
Nort-sur-Erdre
Notre-Dame-des-Landes
Nozay
Orée d'Anjou
Orvault
Oudon
Pannecé
Paulx
Petit-Mars
Pont-Saint-Martin
Port-Saint-Père
Puceul
Remouillé
Rezé
Riaillé
Rouans
Saffré
Saint-Aignan-Grandlieu
Saint-Colomban
Sainte-Luce-sur-Loire
Sainte-Pazanne
Saint-Étienne-de-Mer-Morte
Saint-Étienne-de-Montluc
Saint-Fiacre-sur-Maine
Saint-Herblain
Saint-Hilaire-de-Chaléons
Saint-Hilaire-de-Clisson
Saint-Jean-de-Boiseau
Saint-Julien-de-Concelles
Saint-Léger-les-Vignes
Saint-Lumine-de-Clisson
Saint-Lumine-de-Coutais
Saint-Mars-de-Coutais
Saint-Mars-du-Désert
Saint-Philbert-de-Bouaine
Saint-Philbert-de-Grand-Lieu
Saint-Sébastien-sur-Loire
Sautron
Sucé-sur-Erdre
Teillé
Thouaré-sur-Loire
Trans-sur-Erdre
Treillières
Vallet
Vay
Vertou
Vieillevigne
Vigneux-de-Bretagne
Villeneuve-en-Retz
Vue

**Comment by florianpanchout** [comment]
@l-vincent-l besoin d'une propriété dans Sendinblue pour savoir si je l'affiche ou non

**Comment by l-vincent-l** [comment]
Il y a un attribut `POLLINARIUM_SENTINELLE`

**Comment by florianpanchout** [comment]
Done

**Comment by annepoirot** [comment]
En fait je n'avais pas vu mais il y avait beaucoup plus de villes concernées ! J'ai tout un tableau excel avec les villes par chaque pollinarium présent.
[Communes associees pollinariums 2021 - Recosa nte.xlsx](https://github.com/betagouv/recosante-mail/files/6974120/Communes.associees.pollinariums.2021.-.Recosa.nte.xlsx)
