### ISSUE TITLE
Ajouter les polluants à l'indice ATMO

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#39]
Niveau design je reprendrais celui du widget.

**Comment by florianpanchout** [comment]
@l-vincent-l Besoin de propriétés Sendinblue pour chacun des polluants

**Comment by l-vincent-l** [comment]
De nouveaux attributs ont été ajouté à Send in Blue.
Pour chaque polluant (SO2, NO2, O3, PM10, PM25), il y a deux nouveaux attributs : 
 * SS_INDICE_NOMPOLLUANT_COULEUR
 * SS_INDICE_NOMPOLLUANT_LABEL
 
C’est laborieux, mais Send in Blue ne permet pas d’ajouter des attributs de type dict

**Comment by florianpanchout** [comment]
J'ai ajouté le détail des polluants au template. Ils s'affichent de façon verticale (et pas horizontale comme sur le widget, contrainte technique du mail).

Les attributs sont vides pour l'instant. Donc je n'affiche rien

@l-vincent-l le template attends les mêmes labels que pour QUALITE_AIR :
- Bon
- Moyen
- Dégradé
- Mauvais
- Très Mauvais
- Extrêmement Mauvais

et je n'utilise pas SS_INDICE_NOMPOLLUANT_COULEUR

**Comment by florianpanchout** [comment]
Problème d'affichage dans le template corrigés (affichage des bon intitulés, ajout de O3, centrage des indicateurs
