### ISSUE TITLE
Bug d'affichage newsletter

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#40]
Je crois qu'on a déjà eu ce bug non ?
<img width="544" alt="Capture d’écran 2021-07-20 à 09 47 13" src="https://user-images.githubusercontent.com/63290799/126282453-85f9dc58-76a7-4d1c-b267-7dcb0411432b.png">

**Comment by florianpanchout** [comment]
My bad. Je ne sais pas comment cette image est revenue. C'est corrigé
