### ISSUE TITLE
Modifier la phrase d'introduction du mail pour le radon

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#48]
La phrase serait : 

Aujourd’hui, votre recommandation est un conseil pratique pour prévenir la présence de radon dans l’air intérieur de votre logement qui se situe dans une commune au potentiel radon faible/moyen/élevé.

Il faut donc mettre une variable pour les trois catégories de zone. 

Pour Vincent : mettre cet objectif dans l'ajout de recos

**Comment by florianpanchout** [comment]
On avait pas dit que les introductions Radon commençaient par une explication de ce qu'est le radon ? C'est pour ça qu'on avait mis "Aujourd’hui, votre recommandation est un conseil pratique pour" dans la base. Pour pouvoir le changer si besoin selon la reco ?

**Comment by annepoirot** [comment]
Alors cette option a du se perdre à un moment dans les échanges. J'avais gardé en tête que c'était pour pouvoir mettre le niveau de potentiel radon dans la phrase d'intro. 

Pour ce qui est de la définition du radon, je pense que ce n'est pas nécessaire de la mettre en introduction systématiquement. Normalement les utilisateurs sont censés recevoir les recommandations dans un ordre spécifiques avec la définition du radon dès la première. 

Après on pourrait aussi potentiellement mettre un lien hypertexte sur "radon" qui renvoie vers le site de l'IRSN avec définition ? Ou une page à nous pour éviter de perdre les utilisateurs sur un autre site.

**Comment by florianpanchout** [comment]
Ça marche. Effectivement, je pense qu'il est quand même nécessaire d'avoir au moins un lien d'explication à chaque fois. On ne peut pas être sur que l'utilisateur ait lu le mail précédent (enfin on pourrait mais c'est un autre chantier)

Pourquoi pas un format du style : 

> Aujourd’hui, votre recommandation est un conseil pratique pour prévenir la présence de radon dans l’air intérieur de votre logement. 
[(Qu'est ce que le radon ?)](https://recosante.beta.gouv.fr/potentielradon)

Puis mettre l'info faible/moyen/élevé directement dans la reco serait plus lisible non ?

**Comment by annepoirot** [comment]
Directement dans la reco pourquoi pas, mais du coup où ça ? 
Exemple de reco : 

**Pour réduire les niveaux de radon et garantir une bonne qualité de l’air dans votre logement, aérer les pièces du logement au moins 10 minutes par jour, en toute saison.**

ℹ️ Le radon est un gaz radioactif naturel présent dans le sol et les roches. Il est classé cancérigène certain pour le poumon par le Centre international de recherche sur le cancer depuis 1987. Le potentiel radon fournit un niveau de risque relatif à l'échelle d'une commune. Pour le consulter, l’Institut de radioprotection et de sûreté nucléaire met à disposition une cartographie qui classe les communes en trois zones allant du potentiel faible au potentiel significatif. En savoir plus ici. 
💡 Le potentiel radon d’une commune ne présage en rien des concentrations présentes dans votre habitation : celles-ci dépendent de multiples autres facteurs (étanchéité de l'interface entre le bâtiment et le sol, taux de renouvellement de l'air intérieur, etc.).

**Comment by florianpanchout** [comment]
Pourquoi pas juste : 

**Vous vivez dans une zone au [potentiel radon élevé](https://recosante.beta.gouv.fr/potentielradon). Pour réduire les niveaux de radon et garantir une bonne qualité de l’air dans votre logement, aérer les pièces du logement au moins 10 minutes par jour, en toute saison.**

Ça ne change pas grand chose mais ça permet d'alléger l'introduction

**Comment by annepoirot** [comment]
Les recommandations on été ajoutées dans le catalogue. J'ai dupliquée celles qui valent pour plusieurs zone et j'ai ajouté en début de recommandation le niveau de radon associé. 
Ce qui donne :
<p>📍 Le niveau de risque radon de votre commune est moyen.</p> <p>Pour réduire les niveaux de radon et garantir une bonne qualité de l’air dans votre logement, aérer les pièces du logement au moins 10 minutes par jour, en toute saison. </p>
