### ISSUE TITLE
Le logo de la République française est flou

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#5]

**Comment by florianpanchout** [comment]
Je ne constate pas le problème. Est ce que ce n'est pas juste la compression de Sendinblue ?

**Comment by annepoirot** [comment]
Peut-être... Moi sur le template d'avant j'avais mis le logo ecosante/republique française en svg et ça passait bien dans les mails mais je ne sais pas si là c'est différent

**Comment by annepoirot** [comment]
<img width="624" alt="Capture d’écran 2021-03-16 à 10 16 09" src="https://user-images.githubusercontent.com/63290799/111284812-c3722a00-8640-11eb-99ea-99ead2c93fa5.png">
