### ISSUE TITLE
Modifier le design de la newsletter (indicateurs) quoditienne

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#51]
Il faut un design ou chaque indicateur est associé à une recommandation. 

Pour les premières on ajouterai aussi une information courte sur les changements produit et un renvoi vers la modification du profil.

**Comment by florianpanchout** [comment]
Le template est ici : https://my.sendinblue.com/camp/template/1465/message-setup

Pour les indicateurs en cas d'alertes, j'ai créé une nouvelle issue :  #57

@l-vincent-l J'ai ajouté les attributs `RECOMMANDATION_QA` et `RECOMMANDATION_RAEP` comme vu ici : https://github.com/betagouv/recosante-api/issues/268

**Comment by l-vincent-l** [comment]
J’ai ajouté un attribut NEW_USER

**Comment by florianpanchout** [comment]
Merci ! J'ai modifié le template en fonction

**Comment by florianpanchout** [comment]
Il faut n'afficher que les recommandations dashboard pour chaque indicateur
