### ISSUE TITLE
Envoyer le mail de relance aux utilisateurs avant v2 

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#55]

**Comment by MarinePurson** [comment]
J'ai pas compris :(

**Comment by florianpanchout** [comment]
Avec la nouvelle version il faut prévoir pas mal de mails transactionnels. J'aimerais ne pas en oublier et pouvoir tous les développer d'un coup.

Pour l'instant je pense à : 
- Newsletter hebdomadaire
- Indicateurs
- Newsletter hebdomadaire + indicateurs (si la personne à choisi les indicateurs quotidiens par mail
- Confirmation d'inscription aux indicateurs 
- Confirmation d'inscription aux indicateurs et à la newsletter
- Lien pour éditer son profil
- Mail pour prévenir nos utilisateurs actuels des changements
- Mail de relance pour s'inscrire à la newsletter (si seulement inscrit aux indicateurs)
- Mail pour activer les notifications (si l'utilisateur choisit de recevoir des notifications mais n'accepte pas les notifications sur son device)

Tu en vois d'autres ?

**Comment by florianpanchout** [comment]
Ce serait chouette oui :)

**Comment by florianpanchout** [comment]
On peut le savoir de suite. Par contre c'est peut être plus simple à gérer de faire les envois séparément

**Comment by florianpanchout** [comment]
Est ce qu'il ne serait pas temps de renvoyer un mail pour les utilisateurs qui n'ont pas ouvert le premier mail ?

Voir même, si on est des pro des stats : passer automatiquement tous les gens qui n'ouvrent plus le mail quotidien (et qui n'ont pas ouvert les mails d'annonces) en fréquence alerte. Ils ne sont visiblement pas intéressés par les indicateurs quotidiens donc autant leur mettre automatiquement ce qu'ils pourraient préférer.

L'objectif étant d'endiguer le nombre de descriptions

**Comment by annepoirot** [comment]
Concernant les désabonnements : 
- **On envoie un mail la semaine du 20 décembre aux utilisateurs qui se sont inscrits avant la nouvelle version du 14 octobre ET qui n'ont pas ouvert le mail d'information du 14 octobre.** 
- Le mail les informe que s'ils souhaitent continuer a recevoir tous les jours, ils doivent cliquer sur le bouton. S'ils ne cliquent pas sur le bouton, ils seront automatiquement passé en fréquence alerte.

**Comment by annepoirot** [comment]
Template du mail de relance : 
https://app.sendinblue.com/rnb-editor/index/id/1696

**Comment by annepoirot** [comment]
Le lien renvoie vers la page profil avec une modale qui s'affiche "vos préférences ont bien été pris en compte". 
Ensuite on regardera qui a cliqué sur le bouton pour savoir quels utilisateurs restent en quotidien au retour des congés de @l-vincent-l le 6.

**Comment by florianpanchout** [comment]
Finalement j'ai créé une page à part : https://recosante.beta.gouv.fr/quotidien/

Je me dis que comme ça, si on a un problème avec Sendinblue pour tracker les clics, on pourra le faire via les appels à cette page.

**Comment by florianpanchout** [comment]
C'est normal que le bouton du mail envoyé ne renvoie pas vers https://recosante.beta.gouv.fr/quotidien/ ?

**Comment by annepoirot** [comment]
Très étrange moi je n'ai rien touché au template. je modifie
