### ISSUE TITLE
Écrire le mail pour prévenir nos utilisateurs actuels des changements

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#56]
J'ai créé un template et écrit une première ébauche de contenu. C'est visible ici : 

https://my.sendinblue.com/camp/template/1455/message-setup?editor=v6

Je peux refaire des visuels ci-besoin

**Comment by MarinePurson** [comment]
J'ai fait une nouvelle proposition ici en essayant d'être un peu plus synthétique : https://my.sendinblue.com/camp/template/1489/message-setup
(pour ne pas supprimer la tienne)

Est-ce que le pour le dashboard, on reprendrait pas une incrustation dans un écran comme tu as fait pour les visuels de com ?

**Comment by MarinePurson** [comment]
J'ai corrigé les dernières coquilles et ajusté des détails d'espaces entre les blocs, c'est bon pour envoi de mon côté.
