### ISSUE TITLE
Erreur d'envoi du mail indicateurs

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#59]
Le temps de mise à jour des données des profils utilisateurs sur sendinblue est trop long, rendant impossible l'envoi de la NL. Vincent est en train de regarder pour comprendre pourquoi.

**Comment by l-vincent-l** [comment]
J’ai changé hier la façon dont les contacts s’importent.

Avant je mettais à jour les contacts un à un, cette manière de faire prenait avant une demi-heure. J’ai coupé l’împort hier après deux heures sans que le process ne soit finit.

Hier j’ai changé la façon de faire, je leur envoie maintenant un fichier avec tous les contacts à mettre à jour.
L’import s’effectue bien à ceci près qu’à la fin de l’împort ils sont supposés faire un appel à l’API pour que je déclenche l’envoi de la newsletter, mais je n’a pas reçu cet appel ce matin.

Je leur demande s’ils savent pourquoi l’appel ne s’est pas fait

**Comment by florianpanchout** [comment]
Alors il semblerait que l'appel se soit bien fait puisque la newsletter a été envoyé. Par contre SHOW_QA et SHOW_RAEP sont vides

**Comment by l-vincent-l** [comment]
J’ai fait l’appel à la main ce matin.
Je regarde pour le `SHOW_QA` et le SHOW_RAEP`
