### ISSUE TITLE
Remplacer les logo des partenaires en bas à droite

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#6]
Au lieu de "Ils nous accompagnent" et des logos, mettre :

"Les données utilisées par Recosanté nous sont fournies par" 
Le Réseau national de surveillance aérobiologique (lien vers : https://www.pollens.fr/) 
[le nom de l'AASQA concernée selon la région]. (lien vers l'AASQA)

**Comment by florianpanchout** [comment]
Fait

**Comment by florianpanchout** [comment]
@l-vincent-l Je ne trouve pas le nom de l'AASQA dans les proprietés sur Sendinblue

**Comment by l-vincent-l** [comment]
Les noms des AASQA sont maintenant dans le champ NOM_AASQA des newsletters

**Comment by florianpanchout** [comment]
Fait
