### ISSUE TITLE
Bug d'affichage dans le mail de confirmation d'inscription

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#62]
<img width="525" alt="Capture d’écran 2021-11-02 à 12 27 38" src="https://user-images.githubusercontent.com/63290799/139838152-78ad952e-40f9-428b-801e-03e4141acf5e.png">

- [ ] ajouter un attribut

**Comment by l-vincent-l** [comment]
C’est modifié, l’utilisateur reçoit maintenant
![image](https://user-images.githubusercontent.com/2757318/140093977-926b90c3-7b78-4c32-92da-f28f5fb6f4b2.png)
