### ISSUE TITLE
Affichage des épisodes de pollution dans le mail indicateur

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#63]
#### Back
- [x] Ajouter un attribut dans Sendinblue pour les recommandations liées à l'épisode de pollution (`RECOMMANDATION_EPISODE` ?)
- [x] Bien envoyer la bonne recommandation selon l'épisode en cours
- [x] Afficher les recommandations classiques pour l'indice ATMO
- [x] Changer l'attribut `polluant` pour afficher les polluants au format `PM10, O3 et NO2`

#### Front 
- [x] Afficher la recommandation liée à l'épisode dans le bloc rouge

**Comment by annepoirot** [comment]
> #### Back
> * [ ]  Ajouter un attribut dans Sendinblue pour les recommandations liées à l'épisode de pollution (`RECOMMANDATION_EPISODE` ?)
> * [x]  Bien envoyer la bonne recommandation selon l'épisode en cours => Normalement c'est bon côté recommandation, c'était dans l'admin qu'il y avait des doublons qui n'étaient pas correctes. Maintenant les seules recommandations dans l'admin qui ont un filtre épisode de pollution sont les bonnes. 
> * [ ]  Afficher les recommandations classiques pour l'indice ATMO => on enlève la recommandation d'indice atmo, non ? ca peut porter à confusion si on a déjà les recommandations de l'épisode de pollution plus haut. 
> * [ ]  Changer l'attribut `polluant` pour afficher les polluants au format `PM10, O3 et NO2`
> 
> #### Front
> * [ ]  Afficher la recommandation liée à l'épisode dans le bloc rouge
> * [ ]  Enlever le bouton `En savoir plus` => ok pour ça @mariegasnier1 @MarinePurson ?
>* [ ] Changer la phrase "Un épisode de pollution au `polluant` est prévu aujourd'hui" => je sais que ATMO nous avait demandé de ne pas être commune car les épisodes de pollution sont déclenchés au niveau du département...

**Comment by florianpanchout** [comment]
>  je sais que ATMO nous avait demandé de ne pas être commune car les épisodes de pollution sont déclenchés au niveau du département...

Sauf dans ce cas : https://github.com/betagouv/recosante-api/issues/182

Il faut donc choisir entre : 
- soit ajouter un nouvel attribut avec la zone de l'épisode de pollution
- soit afficher toujours la commune (parce que si c'est valable au niveau du département, c'est valable au niveau de la commune ?)

**Comment by MarinePurson** [comment]
Sur le bouton "En savoir plus", je vois pas en quoi il est gênant sachant qu'il me permet d'avoir plus d'info sur Airparif.
Mais j'ai pas suivi tous vos échanges donc si vous trouvez pertinent de le supprimer, je vous fais confiance.

**Comment by florianpanchout** [comment]
Pareil, je ne pense pas que ce soit nécessaire de le supprimer (et en plus ATMO sera content)

**Comment by annepoirot** [comment]
Ok pour garder le bouton "en savoir plus". Et pour commune vs département => le plus simple serait effectivement de mettre commune mais sachant qu'on sait déjà que ATMo souhaite qu'on mettre département est-ce que ce n'est pas se rajouter du travail pour rien (vu que Delphine va probablement revenir vers nous)

**Comment by florianpanchout** [comment]
@l-vincent-l `RECOMMANDATION_EPISODE` est le même que `RECOMMANDATION_RAEP` pour l'instant

**Comment by florianpanchout** [comment]
> Ok pour garder le bouton "en savoir plus". Et pour commune vs département => le plus simple serait effectivement de mettre commune mais sachant qu'on sait déjà que ATMo souhaite qu'on mettre département est-ce que ce n'est pas se rajouter du travail pour rien (vu que Delphine va probablement revenir vers nous)

@annepoirot Du coup on intègre un nouvel attribut spécifique à la zone de validité de l'épisode de pollution ? Département pour la plupart des régions, ville pour Auvergne Rhône Alpes (https://github.com/betagouv/recosante-api/issues/182)

**Comment by annepoirot** [comment]
Oui ça me convient

**Comment by annepoirot** [comment]
Du coup il reste : 
- ajouter un nouvel attribut spécifique à la zone de validité de l'épisode de pollution => département pour la plupart des régions, ville pour Auvergne Rhône Alpes => Pour le moment on laisse département pour pouvoir passer en prod.
- ajouter `RECOMMANDATION_EPISODE` dans le bloc rouge @l-vincent-l s'en occupe puis passe en prod

**Comment by florianpanchout** [comment]
`RECOMMANDATION_EPISODE` est le même que `RECOMMANDATION_RAEP` (reçu sur mon mail `florian.panchout@gmail.com` aujourd'hui). Ce qui semble être le même problème que https://github.com/betagouv/recosante-mail/issues/63#issuecomment-971313856.

Je ne retrouve pas de trace de l'affichage de `RECOMMANDATION_EPISODE` dans le template mail. L'ajout a été fait directement dans Sendinblue ?

Et le mot "département" est toujours en dur dans le template

**Comment by fcoufour** [comment]
1) On n'a pas l'historique pour un contact côté SIB mais actuellement `RECOMMANDATION_EPISODE` a strictement la même valeur que `RECOMMANDATION_RAEP` : `<ul> <li>En cas de gêne respiratoire ou cardiaque, prendre conseil auprès d’un professionnel de santé... privilégier les activités modérées.</li> </ul>`.

Côté admin, je vois ceci pour dans un cas d'épisode de pollution au dioxyde d'azote, au dioxyde de soufre ou aux particules fines mais pas dans le cas d'alerte aux pollens :
<img width="941" alt="reco_episode" src="https://user-images.githubusercontent.com/23194091/149896774-9246299d-7f36-46b8-966b-5e80b5303d4b.png">

Côté API, si on se remet dans les conditions du direct, il y avait 2 recommandations différentes :
```
"episodes_pollution": {
    "advice": {
        "details": "",
        "main": "<ul>\n<li>En cas de g\u00eane respiratoire ou cardiaque, prendre conseil aupr\u00e8s d\u2019un professionnel de sant\u00e9.</li>\n<li>Privil\u00e9gier des sorties plus br\u00e8ves et celles qui demandent le moins d\u2019effort.</li>\n<li>R\u00e9duire, voire reporter, les activit\u00e9s physiques et sportives intenses (dont les comp\u00e9titions).</li>\n</ul>\n<p>Si vous \u00eates une personne sensible ou vuln\u00e9rable :</p>\n<ul>\n<li>prendre conseil aupr\u00e8s de votre m\u00e9decin pour savoir si votre traitement m\u00e9dical doit \u00eatre adapt\u00e9 le cas \u00e9ch\u00e9ant ; </li>\n<li>\u00e9viter les zones \u00e0 fort trafic routier, aux p\u00e9riodes de pointe ;</li>\n<li>privil\u00e9gier les activit\u00e9s mod\u00e9r\u00e9es.</li>\n</ul>"
    },
},
"raep": {
    "advice": {
        "details": "<p>\u2139\ufe0f Les cheveux retiennent les pollens et gramin\u00e9s qui vont se d\u00e9poser sur\nl'oreiller, ce qui peut g\u00eaner la respiration pendant le sommeil.</p>\n<p>\ud83d\udca1Apr\u00e8s une douche ou un bain ne pas oublier d'a\u00e9rer la pi\u00e8ce.</p>",
        "main": "<p>En saison pollinique, brosser ou rincer ses cheveux avant de se coucher le\nsoir.</p>"
    },
}
```

Donc vraisemblablement un souci avec la mise à jour de la variable RECOMMANDATION_RAEP sur nos contacts.

2) Concernant commune / département, l'API renvoie ceci pour ARA. Qu'est-ce qui n'est pas OK ?
```
"sources": [{
    "label": "Atmo Auvergne-Rh\u00f4ne-Alpes",
    "url": "https://www.atmo-auvergnerhonealpes.fr/"
}],
"validity": {
    "area": "le bassin d\u2019air Bassin Grenoblois",
    "end": "2022-01-16T12:29:59",
    "start": "2022-01-15T12:30:00"
}
```

3) De ce que je comprends, il y a des modifications différentes qui ont été apportés entre template SIB et ici https://github.com/betagouv/recosante-mail/blob/master/src/pages/indicateurs.html ?

**Comment by florianpanchout** [comment]
> Concernant commune / département, l'API renvoie ceci pour ARA. Qu'est-ce qui n'est pas OK ?

Il faut que cette valeur ("le bassin d\u2019air Bassin Grenoblois") soit dans Sendinblue pour pouvoir l'afficher dans l'email. (d'ailleurs ce serait peut être plus correct de dire "le bassin d'air Grenoblois" ?)

> De ce que je comprends, il y a des modifications différentes qui ont été apportés entre template SIB et ici https://github.com/betagouv/recosante-mail/blob/master/src/pages/indicateurs.html ?

Yes, je ne retrouve pas l'affichage de `RECOMMANDATION_EPISODE`. S'il y a d'autre modification qui ont été faite directement dans Sendinblue j'ai besoin de le savoir avant de travailler dessus pour ajouter la vigilance météo.

**Comment by florianpanchout** [comment]
Sur le mail d'alerte (épisode de pollution) reçu pour Grenoble le 30/01 : 

On me prévient d'un épisode de pollution au PM10 et dans l'indice ATMO c'est PM2.5 qui est en mauvais.

<img width="510" alt="Screenshot 2022-02-02 at 11 20 04" src="https://user-images.githubusercontent.com/8115933/152135683-a2ad1bff-515b-4ddb-978b-1b287ced6b50.png">

Après vérification j'ai aussi un problème de cohérence pour les mails du 28/01, du 16/01, du 15/01 et du 23/12

**Comment by annepoirot** [comment]
Qu'est ce qu'on voit dans l'APi de notre côté @fcoufour ou @l-vincent-l ?

**Comment by fcoufour** [comment]
On renvoie ce qui est affiché. Je partage l'incompréhension utilisateur en tout cas. C'est un problème plus profond.
La source transmet un code_pol qui précise la nature de l'épisode et qui vaut 5.
Peut-être y-a-t'il une signification légèrement différente selon les AASQA, du genre particules fines au sens large et pas PM10 ici ?

**Comment by fcoufour** [comment]
Pour info, c'est bien documenté comme Particules PM10 dans le libellé du fournisseur : https://data-atmoaura.opendata.arcgis.com/datasets/17db246020cc4c1c8b2556543e36299f_0/explore?filters=eyJjb2RlX3pvbmUiOlsiMjAwMCJdfQ%3D%3D&showTable=true

**Comment by fcoufour** [comment]
Peut-être un point à éclaircir avec l'AASQA du coup @annepoirot

**Comment by florianpanchout** [comment]
Je pense qu'il y a aussi un problème d'indice ATMO pas à jour au moment de l'envoi. Par exemple pour le mail d'alerte du 28/01 j'ai reçu un indice ATMO moyen par email alors que l'API renvoie un indice mauvais (https://api.recosante.beta.gouv.fr/v1/?insee=38185&date=2022-01-28&show_raep=true)

**Comment by fcoufour** [comment]
L'API renvoie le dernier diffusé pour la journée donc tout à fait possible et je confirme que c'est conforme à ce qu'il y a en base. La dernière publication était plus une correction qu'une prévision
Difficile de présager de la véracité de l'indice pour retarder l'email
