### ISSUE TITLE
Bug du lien de renvoi vers l'AASQA dans le mail lorsqu'on a pas de données

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#64]
Retour d'un utilisateur pour Francheville. 

Quand je clique sur le lien qui est dans le mail qu'il a reçu, ça me renvoie vers : https://recosante.beta.gouv.fr/places//Francheville

**Comment by florianpanchout** [comment]
@l-vincent-l Il manque `VILLE_CODE` dans les attributs contact
