### ISSUE TITLE
Envoi de la vigilance météo

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#65]
#### Quotidien
On envoie la vigilance dès la vigilance verte avec les recommandations associées comme pour le dashboard
#### Alertes 
On envoie à partir de vigilance orange avec les recommandations associées comme pour le dashboard

#### Quotidien : 
On envoie à partir de la vigilance verte.
    - Si vigilance verte, on affiche : "Vigilance météo: pas de vigilance météo"
    - A partir de jaune, on affiche : "Vigilance météo: [liste des types de vigilance en cours]" 
#### Alertes : 
On envoie à partir d'une vigilance orange en affichant "Vigilance météo : [liste des types de vigilance en cours]"

Voir PR côté API : https://github.com/betagouv/recosante-api/pull/328

**Comment by annepoirot** [comment]
On considère que dès lors qu'il y a une vigilance orange ou rouge dans la journée, on envoie le matin.

**Comment by l-vincent-l** [comment]
Du coup j’ai une question s’il y a une vigilance jaune neige je mets : 
"Vigilance météo : jaune neige " ? ou bien "Vigilance jaune neige" ?

S’il y a une vigilance jaune inondation et une vigilance rouge orages je mets 
"Vigilances météo : rouge orage et jaune inondation" ? Ou bien "Vigilance météo : rouge orage" ?

**Comment by annepoirot** [comment]
Du coup pour récapituler : 

- Pour le mail : 
**Quotidien** : on envoie vigilance verte, jaune, orange, rouge. On a des recommandations que pour la vigilance orange et rouge.
**Alerte** : on envoie vigilance orange et rouge. Avec les recos associées. 

- Pour les notifications : 
**Quotidien** : on envoie vigilance verte, jaune, orange, rouge. Pas de reocmmandations mais un lien "en savoir plus" vers le dahsboard. On envoie le texte suivant : "Vigilance météo : [niveau de vigilance]". Ca donnerait par exemple "Vigilance météo : orange". On ne précise pas le type de vigilance.
**Alerte** : on envoie vigilance orange et rouge. Pour le reste, pareil que pour quotidien.

**Comment by annepoirot** [comment]
Pour le mail cela s'affichera comme sur le dashboard :
Capture d’écran 2021-12-20 à 10 48 49
Donc il faut afficher:

le niveau de vigilance global
les différents niveau de vigilance par catégorie (de jaune, orange et rouge)
les recommandations (que en cas de orange et rouge)
Pour les alertes, on envoie à partir de la vigilance orange.
Pour la notification, on ne va finalement pas donner le détail du type de vigilance, seulement le niveau et s'ils souhaitent en savoir plus ça renvoie au dashboard.

**Comment by annepoirot** [comment]
Cas d'aujourd'hui : vigilance jaune affichée par météo france car elle commence le 04/01. Or nous on affiche pas de vigilance.

**Comment by florianpanchout** [comment]
Pour quelle ville ?

**Comment by annepoirot** [comment]
Biarritz

**Comment by florianpanchout** [comment]
Ce point est traité ici non https://github.com/betagouv/recosante/issues/167 ?

**Comment by annepoirot** [comment]
Oui, on a fait un doublon avec Franck !

**Comment by annepoirot** [comment]
![Vigilance_pictos_2021](https://user-images.githubusercontent.com/63290799/150752933-4a012640-9994-4323-90f7-d64586657763.jpg)
Les pictogramme @florianpanchout

**Comment by fcoufour** [comment]
Tu as autre chose qu'un format compressé car les images ont l'air d'être de bonne qualité ?

**Comment by fcoufour** [comment]
Format SVG, EPS, AI ou un PNG haute résolution pour chaque icône

**Comment by annepoirot** [comment]
Ils m'ont envoyé deux fichiers similaires à celui ci donc avec l'ensemble des icône, un en JPEG et l'autre en PNG

**Comment by fcoufour** [comment]
Vu ce qu'on en fait, la version PNG devrait suffire

**Comment by florianpanchout** [comment]
Nouveau template avec la vigilance météo : https://my.sendinblue.com/camp/template/1959/message-setup

Il manque comme attributs : 
`SHOW_VIGILANCE`
`VIGILANCE_VALIDITE`

`VIGILANCE_[NOM]_COULEUR` attend les valeurs `Rouge`, `Orange` ou `Jaune` pour afficher les pictos correspondants.

Je me base sur la présence de `VIGILANCE_[NOM]_RECOMMANDATION` pour savoir si j'affiche ou non la vigilance

**Comment by fcoufour** [comment]
Merci @florianpanchout, on va faire les ajustements nécessaire côté API et sur le template.

**Comment by annepoirot** [comment]
Du coup il faut ajouter l'envoi de la vigilance dans les notifications @l-vincent-l

**Comment by fcoufour** [comment]
J'ai apporté quelques petites modifications à la proposition de Florian. La PR est ici : https://github.com/betagouv/recosante-mail/pull/90

Les travaux pour Vigilance Météo et Indice UV ont été regroupés dans un seul template SIB : https://my.sendinblue.com/camp/template/1794/message-setup.

Voici ce que ça donne pour selon le niveau de vigilance :
<img width="561" alt="nl-vigilance-verte" src="https://user-images.githubusercontent.com/23194091/154495204-7f51dfa4-555e-4398-aa66-6baa39a74dda.png">
<img width="549" alt="nl-vigilance-jaune" src="https://user-images.githubusercontent.com/23194091/154495234-9d0ecf08-b1fa-499b-aa4f-35240fe78ded.png">
<img width="588" alt="nl-vigilance-orange" src="https://user-images.githubusercontent.com/23194091/154495248-9aa6b021-33de-4ada-952d-ef091e210eda.png">
<img width="592" alt="nl-vigilance-rouge" src="https://user-images.githubusercontent.com/23194091/154495260-80d7e244-b8ad-4fbe-a18c-10fb53c284a2.png">

TODO :
- notifications web
- envoyer les dates dans les attributs déjà formatées
