### ISSUE TITLE
Ajouter une question pour feedback dans la newsletter hebdo

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#69]

**Comment by MarinePurson** [comment]
Avec la newsletter, on a deux objectifs d'impacts : 
- enrichir les connaissances et la compréhension
- permettre d'agir

Du coup, il faudrait trouver une question pour mesurer l'impact.
- Est-ce que ces contenus vous ont intéressé ?
- Est-ce que cette lettre d'information vous a été utile ?
- Avez-vous appris quelque chose ? 
- ...

**Comment by annepoirot** [comment]
On choisit : Ces contenus vous on-t-il été utiles ? oui/non

**Comment by annepoirot** [comment]
On peut utiliser le même appel à l'API

**Comment by florianpanchout** [comment]
J'ai créé un nouveau bloc "Avis". Il est intégré en exemple dans ce template : https://my.sendinblue.com/camp/template/1688/message-setup?editor=v6
