### ISSUE TITLE
Ajouter une phrase sur la sensibilisation pollens/QA

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#7]

**Comment by florianpanchout** [comment]
@annepoirot Il me faudrais la phrase à afficher :)

**Comment by annepoirot** [comment]
Haha oui désolée je voulais faire ça ce matin

**Comment by annepoirot** [comment]
Du coup l'idée serait d'afficher la phrase suivante dans la newsletter : 
La qualité de l'air peut aggraver les symptômes allergiques, veillez à être encore plus attentif à cette recommandation.

On souhaiterait l'afficher à la suite de la recommandation. 

Elle est conditionnée par :
- la recommandation affichée : elle ne s'affiche que lorsque c'est une recommandation pollen qui est envoyée.
- les indicateurs environnementaux et le profil utilisateur : 
    -- pour les personnes allergiques : elle est envoyée lorsque l'indice ATMO est de dégradé à extrêmement mauvais ET que le RAEP est égal ou supérieur à 1. 
    -- pour les personnes non allergiques : elle est envoyée lorsque l'indice ATMO est de dégradé à extrêmement mauvais ET que le RAEP est égal ou supérieur à 4.

Qu'en pensez vous ? On peut se mettre ça pour le sprint prochain sans soucis.

**Comment by florianpanchout** [comment]
@l-vincent-l Il me faut une variable pour conditioner son affichage

**Comment by annepoirot** [comment]
Yes je pense que pour le moment on le met de côté et on l'ajoutera à l'avenir si c'est ok de votre côté

**Comment by annepoirot** [comment]
Du coup pour cette issue : 

On souhaite afficher la phrase suivante : "Une mauvaise qualité de l'air peut aggraver les symptômes allergiques, veillez à être encore plus attentif à cette recommandation."

UNIQUEMENT lorsque les recommandations suivantes sont envoyées à un utilisateur : https://pad.incubateur.net/TYqfXTvZTLKjMOOdI_cOoQ

**Comment by l-vincent-l** [comment]
Un attribut sendinblue `LIEN_QA_POLLEN` a été ajouté, la liste des recommandations liées est consultable ici https://ecosante.beta.gouv.fr/recommandations/?search=&categories=lien_qa_pollen&status=published&objectif=None&type=None

**Comment by florianpanchout** [comment]
C'est fait
