### ISSUE TITLE
Envoyer la troisième newsletter hebdo

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#73]
https://my.sendinblue.com/camp/template/1688/message-setup

**Comment by l-vincent-l** [comment]
Le template a été ajouté, ainsi qu’une nouvelle page dans l’admni pour les ajouter et les modifier

**Comment by annepoirot** [comment]
Bug d'envoi aujourd'hui : envoi de la n°2 au lieu de la n°3.

On ne renvoie rien aujourd'hui du coup, on décale à la semaine prochaine. pour le jeudi 23 décembre, les personnes qui auraient du recevoir la n°3 aujourd'hui mais ne l'ont pas reçue la recevront. 

Est-ce qu'on peut programme un envoi le 30 ou bien tu préfères qu'on décale pour éviter un risque de bug ? @l-vincent-l

**Comment by annepoirot** [comment]
Pour le mail cela s'affichera comme sur le dashboard :
<img width="607" alt="Capture d’écran 2021-12-20 à 10 48 49" src="https://user-images.githubusercontent.com/63290799/146747381-9995de89-52e1-4dfa-9f83-a55f06ddf01e.png">
Donc il faut afficher:
- le niveau de vigilance global
- les différents niveau de vigilance par catégorie (de jaune, orange et rouge)
- les recommandations (que en cas de orange et rouge)
- Pour les alertes, on envoie à partir de la vigilance orange.

Pour la notification, on ne va finalement pas donner le détail du type de vigilance, seulement le niveau et s'ils souhaitent en savoir plus ça renvoie au dashboard.
