### ISSUE TITLE
Envoi du questionnaire de satisfaction

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#77]
On en avait parlé lors du dernier point mensuel, on souhaiterait envoyer un bilan 2021 à nos utilisateurs avec des données rétrospectives sur l'année passée.

On souhaiterait avoir les données suivantes : 
- Le niveau d'indice ATMO le plus présent dans leur ville. (ici on va devoir créer une définition de ce qu'est un indice moyen car c'est probablement ce qui va le plus ressortir).
- Le nombre de pics de pollutions et quels polluants principaux (renvoyer vers une page de définition de polluant, on a déjà ça non ?)
- Le risque d'allergie au pollen le plus plus présent dans leur ville
- Le nombre de pics polliniques dans leur ville et les principaux pollens.

On pensait utiliser ce mail pour faire passer le questionnaire utilisateur. 

On souhaiterait l'envoyer le **jeudi 6 janvier**, à la place de la newsletter hebdomadaire. 

Du coup il faudrait : 
- [x] Préparer le template : @florianpanchout  est-ce que ça te semble faisable niveau temps ? 
- [ ] Récupérer les données : @l-vincent-l  ça te semble jouable d'avoir ce type de données ? Pour les données RAEP, on a l'historique depuis quand ? 
- [ ] Rédiger le questionnaire utilisateurs : on s'en charge avec Marine
- [ ] Programmer l'envoi : @l-vincent-l est-ce que c'est pas trop galère que ça remplace une NL hebdo ?

**Comment by florianpanchout** [comment]
Oui sans problème pour le template

**Comment by annepoirot** [comment]
Problème : on a pas toutes les données de l'année sauvegardées en base => ça prendrai trop de temps. A voir ce qu'on fait avec @MarinePurson.

@l-vincent-l peut regarder si l'API ATMO renvoie des données depuis janvier 2021 mais sinon il sera sûrement mieux de changer le contenu.

**Comment by annepoirot** [comment]
Comme ça semble complexe de récupérer les indicateurs sur 2021, on partirait sur un mail simple pour transmettre le questionnaire utilisateur : https://pad.incubateur.net/BSIey6nBTD6fvFenyvAgBg?both (ligne 30)

**Comment by MarinePurson** [comment]
J'ai intégré les contenus dans un template : https://app.sendinblue.com/rnb-editor/index/id/1713

Il reste à : 

- [ ] voir si on peut faire quelque chose de plus joli @florianpanchout 
- [ ] intégrer le lien vers le questionnaire utilisateurs @annepoirot 
- [ ] programmer l'envoi

**Comment by florianpanchout** [comment]
J'ai recréé un template pour reprendre la présentation des autres mails : https://my.sendinblue.com/camp/template/1716/message-setup?editor=v6. Pour les prochains mails ce serait plus simple de dupliquer un des mails existants. Ça permettrait de conserver automatiquement le style et la structure.

Je me suis permis d'ajouter des majuscules en début de paragraphe. Je ne suis pas sur que l'on doive respecter la règle de la minuscule après la virgule quand celle ci est dans un titre (et j'ai mis un point entre les deux paragraphes). J'ai aussi ajouté un coeur à "merci pour votre interêt" parce qu'il est un peu tristounet tout seul.

(Est-ce qu'on ne devrait pas souhaiter la bonne année aux gens dans ce mail ?)

**Comment by annepoirot** [comment]
Une première version du questionnaire : https://form.typeform.com/to/tgbsWiub @MarinePurson @florianpanchout

**Comment by florianpanchout** [comment]
Quelques retours en vrac : 

«Êtes-vous abonné·e à Recosanté par mail ou par notification ? » => « Recevez-vous les indicateurs Recosanté par mail ou par notification ? » (ils peuvent recevoir les indicateurs par notifications et la newsletter hebdo par mail donc il faut préciser de quoi on parle ici)

« Si vous êtes abonné·e par mail, quelle option d'affichage préférez-vous parmi ces deux possibilités : » Même chose que pour le dernier sondage : je ne trouve pas pertinent de poser cette question à l’utilisateur. Tournée de cette façon, tout le monde va vouloir plus de détail. C’est parce que l’on est pas capable de fournir des recommandations quotidiennes intéressantes que l’on a switché vers une newsletter hebdomadaire.

« Si non, pour quelle(s) raison(s) n'êtes-vos pas satisfait·e de ce choix ? » les réponse me parlent juste de trop ou pas assez d’information. Si je ne suis pas satisfait du média (et pas de la fréquence), les réponses seront plus du style « je reçois trop de mail » ou « je ne comprends pas pourquoi je ne reçois pas les notifications sur mon téléphone » 

Il y a un problème d’enchainement ensuite avec la question suivante (qui est la même).

« Êtes-vous abonné·e à Recosanté pour recevoir des informations au tous les jours ou en cas d'alerte ? » => « Recevez-vous les indicateurs Recosanté tous les jours ou seulement en cas d’alerte ? » (il faut aussi changer les réponse pour faire disparaitre la mention de mail)


« Etes vous abonné·e à la lettre d'information hebdomadaire reçue tous les jeudi ? » => « Etes vous abonné·e à la lettre d'information hebdomadaire envoyée tous les jeudi ? »

« Pour quelle(s) raison(s) n'êtes-vous pas abonné·e à la lettre d'information hebdomadaire du jeudi ? » => « Pour quelle(s) raison(s) n'êtes-vous pas abonné·e à la lettre d'information hebdomadaire ? » (il manque une réponse « autre »)


Juste après on me demande « Êtes-vous satisfait·e des contenus présents dans la lettre d'information hebdomadaire du jeudi ? », j’imagine qu’il y a un bug d’enchainement.

Question 10 : « Il est disponible sur le site internet Recosanté » => « Il est disponible sur https://recosante.beta.gouv.fr/» 


Question 11 : Il manque une réponse « Autre »

**Comment by florianpanchout** [comment]
En fait, la question que je me pose c’est : « qu’est ce que l’on souhaite apprendre de ce sondage ? ». Je n’ai pas l’impression de pouvoir faire grand chose des réponses à ces questions.

Déjà, j’attendrais la fin du mois pour l’envoyer. Dans 2 jours on passe 3000 personnes en alerte plutôt que quotidien, ça risque d’avoir un impact sur le niveau de satisfaction.

Ensuite, je ne sais pas si j’axerais autant les questions sur le service actuel : 
1. les gens votent plus honnêtement avec leurs désabonnements qu’avec un sondage
2. ce qui nous intéresse c’est savoir dans quelle direction aller maintenant (ajouter plus de données ? ajouter les prévisions du lendemain ? ajouter un affichage multi-communes ? etc.). Pas se reprendre la tête pour des trucs qu’on vient à peine d’implémenter

**Comment by annepoirot** [comment]
Ouais je comprends, et je suis alignée sur le fait de faire un questionnaire plus prospectif sur la suite. J'attends que Marine jette un coup d'oeil demain et dans l'aprem je travaillerai sur une autre version. Merci pour tes retours !

**Comment by florianpanchout** [comment]
Pour info le compte Typeform de beta s'arrête le 20 janvier (https://mattermost.incubateur.net/betagouv/pl/mbiyjrguctr3tncuk418per76y)

(Je ne sais pas si c'est ce que tu utilises ici @annepoirot)

**Comment by annepoirot** [comment]
Yes c'était bien là dessus :( Le problème c'est que sur la version gratuite je ne peux pas avoir plus de 100 réponses... Donc soit on paye 55€ mais ça fait cher le questionnaire de satisfaction, soit on passe sur un autre outil.

**Comment by annepoirot** [comment]
Envoi le semaine du 24 avec abonnement typeform payant à 55€
