### ISSUE TITLE
La newsletter s'envoie deux fois le lundi

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#78]
Il est arrivé la même chose lundi dernier le 13 décembre.

**Comment by annepoirot** [comment]
>À la fin de l’export je dis à sendinblue d’appeler une API chez nous qui déclenche la création et l’envoi de la campagne, et cet appel était fait deux fois. Mais maintenant j’empêche la re-création de campagne si la une campagne avec la mailingliste a déjà été envoyé

**Comment by florianpanchout** [comment]
@l-vincent-l en lien avec https://github.com/betagouv/recosante-mail/issues/80 ?
