### ISSUE TITLE
Remettre en place l'envoi du mail indicateur vide à 14h si l'on a pas les données

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#79]
Lorsqu'un jeu de données bug, il ne s'envoie pas dans le mail ou la notif. 

Il pourrait être utile de rajouter un message le premier jour du bug qui dirait "Les données ne sont pas disponibles aujourd'hui" avec un blabla qui sous entend que ce n'est pas de notre faute haha. 

Il faudrait que ce soit une modale plutôt qu'un template en entier.

**Comment by florianpanchout** [comment]
Pas sur de comprendre. Le cas ou l'indice ATMO n'est pas disponible est déjà pris en compte dans le mail. Tu veux que l'on change ce texte la ?

**Comment by annepoirot** [comment]
Ah oui ? Parce que dans le cas de ATMO Normandie on a pas les données depuis mercredi et par exemple Franck n'a pas reçu de newsletter du coup

**Comment by florianpanchout** [comment]
Normalement si on a pas les données à 14h on envoie le mail sans la QA non ? @l-vincent-l

**Comment by annepoirot** [comment]
Oui c'est ce que j'avais en tête aussi, mais du coup si la personne est inscrite que à la QA elle ne reçoit pas du tout de mail si l'indice bug pendant plusieurs jours comme c'est le cas pour ATMO Normandie en ce moment.

**Comment by florianpanchout** [comment]
Non, l'envoi du mail se fait sans la QA mais avec un message disant que l'indice ATMO n'est pas disponible. Enfin, c'est le comportement attendu en tout cas

**Comment by annepoirot** [comment]
Ok du coup il semble que ça n'ai pas fonctionné

**Comment by fcoufour** [comment]
Coucou @florianpanchout, je confirme les dires d'Anne. Je n'ai rien reçu depuis mercredi et vraisemblablement l'absence de données ATMO pour la Normandie et ma charmante bourgade de Granville. Ce cas est censé être traité dans ce template : https://github.com/betagouv/recosante-mail/blob/master/src/pages/indicateurs.html ?

**Comment by florianpanchout** [comment]
Yes. Si l'attribut `QUALITE_AIR` est vide on affiche un message spécifique (ligne 247 de ton lien).

"Normalement" l'api vérifie toutes les heures si elle a les données ou non pour pouvoir envoyer email / notification. Si à 14h elle n'a toujours pas les données elle déclenche l'envoi quand même. Je laisse @l-vincent-l me corriger au besoin

**Comment by fcoufour** [comment]
Bien vu ! Je m'étais fait avoir par l'alignement. Du coup, si je comprends bien, étant donné que la Normandie n'a pas eu de données depuis plusieurs jours, j'aurais dû recevoir un email à 14h tous les jours avec pour seul message : "L'indice de qualité de l'air à Granville n'est pas disponible au moment de l'envoi de cet email" donc il y a quelque chose qui ne se passe pas comme prévu au niveau de l'envoi. Vous auriez un suivi unitaire des envois pour recosante@coufourier.com pour vérifier que les emails ne sont pas partis ?

**Comment by annepoirot** [comment]
> Yes. Si l'attribut `QUALITE_AIR` est vide on affiche un message spécifique (ligne 247 de ton lien).
> 
> "Normalement" l'api vérifie toutes les heures si elle a les données ou non pour pouvoir envoyer email / notification. Si à 14h elle n'a toujours pas les données elle déclenche l'envoi quand même. Je laisse @l-vincent-l me corriger au besoin

Ca c'est vrai pour le mail mais pas pour la notification, ce qui explique l'envoie de notifications répétitifs depuis quelque jours. Car en l'absence de données ATMO Normandie l'aglo renvoyait la notif. @l-vincent-l va le corriger

**Comment by fcoufour** [comment]
Je m'auto-réponds. J'ai vérifié sur Sendinblue et dernière campagne envoyée pour mon adresse le mercredi 15 donc confirmation que les emails ne sont pas partis

**Comment by annepoirot** [comment]
Le mail s'envoie bien, il faut simplement changer l'horaire à 15h heure française.
