### ISSUE TITLE
Ajouter les infos manquantes sur Sendinblue

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#8]
Pour les pollens j'ai bien les deux propriétés (couleur et valeur) mais l'une est tout le temps à 0 et l'autre tout le temps à #fff

Pour l'uid, short_id n'a pas l'air d'être le bon

**Comment by florianpanchout** [comment]
(J'ai trouvé USER_UID)

**Comment by l-vincent-l** [comment]
Ce problème est résolu dans le projet principal
