### ISSUE TITLE
Sondage manquant sur le dernier mail

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#82]
Je viens de recevoir la dernière newsletter hebdomadaire (https://my.sendinblue.com/camp/template/1697/message-setup). Elle ne contient pas le bloc sondage. Est-ce un choix délibéré ou un oubli ?

**Comment by annepoirot** [comment]
Non c'est un oubli !

**Comment by annepoirot** [comment]
j'ai ajouté
