### ISSUE TITLE
Recommandation pas adaptée à l'indice ATMO ?

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-mail#86]
En retournant voir l'email reçu samedi, j'ai réalisé que, malgré un indice ATMO mauvais (et un épisode de pollution en cours), ma recommandation parlait d'air intérieur : 
> Ne pas s'exposer à des facteurs irritants (fumée de tabac, utilisation de solvants en espace intérieur, chauffage au bois, exposition aux pollens en saison...).

C'est normal ?

**Comment by annepoirot** [comment]
Yes c'est "normal" dans le sens où c'est une recommandation valide. Je pense que le problème vient peut-être de la tournure, surtout sans les précisions, qui donne l'impression que ça n'a pas de lien.

**Comment by annepoirot** [comment]
On pourrait avoir plutôt : Ne pas aggraver les effets de cette pollution en s'exposant à des facteurs irritants supplémentaires : fumée de tabac, utilisation de solvants en espace intérieur, exposition aux pollens en saison...
