### ISSUE TITLE
Ajouter URL trackée dans le referal de l'email indicateur

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#88]
Il semblerait qu'il n'y ait plus d'URL trackée dans le mail. Les gens cliquent mais ça ne remonte pas sur matomo.
Il y avait déjà une URL, peut-être le mieux c'est de reprendre la même ?

**Comment by annepoirot** [comment]
Mais est-ce que les personnes comptabilisées dans le channel venant de sendinblue ce n'est pas aussi celles qui cliquent par exemple sur le logo recosanté dans le mail ?

**Comment by florianpanchout** [comment]
Ah si totalement. On peut juste savoir que l'utilisateur vient d'un serveur Sendinblue.

Sur quel lien il y avait un utm ? Je ne retrouve de trace de ça nul part dans le repo

**Comment by fcoufour** [comment]
C'est @MarinePurson qui a évoqué le sujet à un point où tu n'étais pas présent donc je complète les infos d'Anne.

Il s'agit de ces boutons en footer de l'email des indicateurs :
<img width="657" alt="referral-email" src="https://user-images.githubusercontent.com/23194091/151547832-c2a9ef00-1da4-4870-86e8-4dab78a9aef4.png">

Ils pointent vers 2 liens sortants "mailto" ou protocole "WhatsApp".
Marine croit se souvenir qu'ils ont été trackés par le passé via une campagne qui porte le nom de "referral".
Est-ce que ça te dit qqch ?

Pour ma part, vu que ce sont des liens sortants, je ne vois pas d'autres options que celles-ci :
- avoir des URLs de redirection côté frontend comme : recosante.beta.gouv.fr/email -> mailto:
- utiliser un plugin Matomo spécifique aux redirections externes

On peut voir ça lundi (je ne travaille pas aujourd'hui) si tu veux @florianpanchout en remettant à plat les templates différents côté SIB et repo. Je vais en avoir besoin pour attaquer l'emailing Indice UV.

**Comment by florianpanchout** [comment]
Aaaah ok

Ce n'est pas le clic sur ces boutons qui est tracké mais le lien dans le message pré-écrit. L'UTM est toujours la (https://github.com/betagouv/recosante-mail/blob/master/src/pages/indicateurs.html#L723 et https://github.com/betagouv/recosante-mail/blob/master/src/pages/indicateurs.html#L716)

Et je vois toujours le tracking remonter dans Matomo (2 clics le 27/01 par exemple)

**Comment by fcoufour** [comment]
Effectivement, commit d'origine ici par Chaïb : https://github.com/betagouv/recosante-mail/commit/da5a05050ab7cc29130ab35690247814709c93b3

A date, y'a plus que dans le message WhatsApp, plus sur l'email par contre (L716).

Pas certain que ce soit très utile de tracker plus avec ça déjà en place.

**Comment by florianpanchout** [comment]
Effectivement. D'ailleurs seul le contenu du mailto est à jour (le message Whatsapp parle encore de newsletter quotidienne)

**Comment by fcoufour** [comment]
Du coup, je maintiens la nécessité de faire une revue du sujet "emailing" ensemble et peut-être avec Anne ou Marine, pour repartir sur des templates propres et que je sois autonome. Lundi après la planif produit ?

**Comment by MarinePurson** [comment]
Propositions pour remplacer les contenus :
- pour le mail : 
**Connaître la qualité de l'environnement autour de toi, ça t'intéresse ?**
Grâce à Recosanté, c'est possible et c'est très facile : tu peux **découvrir en un clic la qualité de l'air, les vigilances météo, le risque d'allergie aux pollens, etc. dans ta commune !**
Si tu le souhaites, tu peux même t'abonner pour recevoir ces informations directement par mail ou par notification. En plus de ça, Recosanté te propose une newsletter hebdomadaire pour mieux comprendre le lien entre ton environnement et ta santé.
**Pour t'inscrire, c'est gratuit et c'est [ici](https://recosante.beta.gouv.fr/?mtm_campaign=referral-mail).**

- pour WhatsApp : 
Tu connais Recosanté ? C'est un service gratuit pour connaître la qualité de l'environnement dans ta commune : qualité de l'air, pollens dans l'air, vigilances météo, etc. Tu peux consulter ces indicateurs environnementaux en ligne ou t'abonner pour les recevoir directement par mail ou par notification. En plus de ça, tu peux choisir de recevoir tous les jeudis une newsletter spéciale pour mieux comprendre les liens entre ta santé et ton environnement.
Pour découvrir Recosanté, c'est par [ici](http://recosante.beta.gouv.fr/?utm_source=referral).
