### ISSUE TITLE
Réduire la taille de l'information sur les données en bas à droite

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-mail#9]
- Mettre une police plus petite car actuellement Recosanté est coupé en deux
- On a l'impression que Airparif est la suite du Réseau national... => peut-être passer l'AASQA en premier ? ou si tu as une autre idée
<img width="624" alt="Capture d’écran 2021-03-16 à 10 16 09" src="https://user-images.githubusercontent.com/63290799/111285061-0af8b600-8641-11eb-96c1-8529819e6a77.png">

**Comment by florianpanchout** [comment]
Fait

**Comment by annepoirot** [comment]
Est-ce qu'on peut mettre plutôt : 

Les données sont fournies par :
Airparif
Réseau national de surveillance aérobiologique

Avec "aérobiologique" à la ligne s'il est coupé

Merci :)

**Comment by florianpanchout** [comment]
Je n'ai pas la main sur la césure sur email. J'ai changé la mise en page pour éviter le problème
